site_name: Bhanu Pratap Sharma, PhD
site_url: https://bhanups1991.github.io/
site_author: Bhanu Pratap Sharma

theme:
  name: material
  palette:
  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: custom-dark
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.tabs.link

nav:
  - Home: index.md
  - About Me: about.md
  - Research Log:
    - Weak Form: weak_form.md
    - Tensors with Bases: tensors_with_bases.md
    - Finite Element Method:
      - Isoparametric Elements: isoparametric_elements.md
      - Geometric Nonlinearity: geometric_nonlinearity.md
    - Signorini Conditions in Contact Mechanics: signorini_conditions.md
    - Piola Traction Decomposition: piola_traction_decomposition.md
    - Consistent Reminders: glossary.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs
  - attr_list
  
plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - javascripts/extra.css